'''
 Tiny validator for V4 json schema in postman goto test>select tiny validator
Postman > Authorization > API Key , Who will generate this key? server will generate a key client server , server
will generate and server will keep through this So by promoter it means while we are testing this Api developer
will provide us the key . [Key mostly generated by the servers] 1.Is a unique string, 2.Server generates it,
3.No real value 4.developer or server will give no idea.[4th point not requied to tell in interviwe]
What is Token :- Means is a temporary key plus limited access.
Bearer:- Means is a unique random string (server has generated it) bearer token is not stored at client side.
1. randon string, 2.expirary have, 3.server only can understand [Can we do decode bearer token? No is server only
can understand]
cookies:- 1. is a key & value pair , 2. cookie store at client side, 3. maximum of them have a expirary,
5. client side , 6. Set cookie method
JWT:- is also called json web token(is also type of beare token (its store some values in bearer type token).1. Contains some data about
client..()
---
To allow to access the API
Cookie:-
1.is basically calient
2.Key and value pair
3.Expiry
4.Client store them
5.Set-cookie method basically used
->API Key:-
1.It is also unique key,
2. server generates it
3.No real value
4.No idea who has given this dev/server/cleint(optipnal dont tell this in interview)
->Bearer
1.random string
2.Start from ey  bla ble
3.Expiry
4.Server only can understand
->JWT
1.contains some data about client
----Cookie, Api key, Bearer tokem server only can give this all
--------
Rest Assured auth 2.0
request auth 20 python
---Some time we need to pass the path parameter to fetch the data.
--Using the path parameter we are just redirecting to the subresource . and where as the poth parameters strats
from the forward salsh.
-- Using Query parameter its just filter the data based upon our request, the query parameter start from the "?"
question mark
---"baseurl/resourse/(pathparameter/queryparameter)"
---For RUn the postman collections through cmd use the newman for that install node.js .Next install newman
steps -> npm install -g newman
--***command is :- newman run "postman->collectionpath"
--Install of Html reporter -> - npm install newman-reporter-html
***command :- newman run path -r html


'''
'''

'''

